<?php

namespace AppBundle\Repository;
use AppBundle\Entity\demandeur;


/**
 * demandeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeurRepository extends \Doctrine\ORM\EntityRepository
{

}
