<?php

namespace AppBundle\Repository;

/**
 * epiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epiRepository extends \Doctrine\ORM\EntityRepository
{

  /*  public function findAll()
     {
         return $this->findBy(array('actif' => 1), array('description' => 'ASC'));
     }
     */
}
