<?php

namespace AppBundle\Repository;

/**
 * ligneDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ligneDRepository extends \Doctrine\ORM\EntityRepository
{
}
