<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Techniciens;
use Doctrine\ORM\EntityRepository;

/**
 * TechniciensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechniciensRepository extends \Doctrine\ORM\EntityRepository
{

/*  public function findAll()
   {
       return $this->findBy(array('actif' => 1), array('nom' => 'ASC'));
   }
*/
}
